const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{chromium}=require('playwright');
const root=__dirname,out=path.join(root,'output/milestones-integration');fs.mkdirSync(out,{recursive:true});
const src=fs.readFileSync(path.join(root,'server.js'),'utf8').replace(/server\.listen\([\s\S]*?\}\);\s*$/,'');
const G=new Function('require','__dirname','setInterval','setTimeout',src+';return {server,rooms,makeFixtureRoom,publicState,resolveTile,updateTitles,startBattle,resolveBattle};')(require,root,()=>0,()=>0);
(async()=>{let browser;try{
 await new Promise(r=>G.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+G.server.address().port;
 const r=G.makeFixtureRoom();r.code='MLST';r.pending={};r.turn=0;r.turnTransition=r.windSupply=r.shopVisit=null;r.owners.fill(null);r.elemOv={};r.tileFx={};r.curses={};r.titles={conqueror:null,pilgrim:null};r.botMode=false;
 for(const key of Object.keys(r))if(key.startsWith('last'))r[key]=null;
 r.players.forEach(p=>{p.hand=[];p.gold=1000;p.battleWins=p.shrineVisits=0;p.name='テスト召喚士一号';});const actor=r.players[0];actor.charId='mio';G.rooms.set(r.code,r);
 browser=await chromium.launch({channel:'chrome',headless:true});const p=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/api/fixture',route=>route.fulfill({contentType:'application/json',body:JSON.stringify(G.publicState(r,null))}));await p.goto(base+'/play?fixture=1&guide=done');await p.waitForFunction(()=>state?.catalog&&window.BoardMilestones);
 const idle=()=>p.waitForFunction(()=>!presentationRunning&&!presentationQueue.length&&!cutBusy&&!gameEntryRunning&&!animBusy&&!finishActiveTelop&&Date.now()>bannerUntil,null,{timeout:45000});await idle();
 const render=async()=>{r.stateRev++;await p.evaluate(s=>{state=s;render();},G.publicState(r,null));};
 // A real acquisition uses the authoritative counter and does not create cash.
 const cash=actor.gold;actor.battleWins=3;G.updateTitles(r);await render();await p.waitForSelector('#boardNotice[data-kind=ms-title]:not([hidden])');assert.match(await p.locator('.msTitleHero').innerText(),/覇者.*戦闘勝利 3勝/s);assert.equal(await p.locator('.msFormer').count(),0);assert.equal(actor.gold,cash);await idle();
 // Queued takeover must keep the old owner even if state receives another update.
 const next=r.players[1];next.name='二番目の召喚士';next.battleWins=5;G.updateTitles(r);await render();await p.waitForSelector('#boardNotice[data-kind=ms-title]:not([hidden])');assert.match(await p.locator('.msFormer').innerText(),/テスト召喚士一号.*−500G/s);assert.equal(await p.locator('#boardNotice').getAttribute('data-actor'),next.id);assert.match(await p.locator('.msTitleHero').innerText(),/5勝/);await idle();await render();await p.waitForTimeout(300);assert.equal(await p.locator('#boardNotice:not([hidden])').count(),0);
 next.shrineVisits=6;G.updateTitles(r);await render();await p.waitForSelector('#boardNotice[data-kind=ms-title]:not([hidden])');assert.match(await p.locator('.msTitleHero').innerText(),/大巡礼者.*6回/s);await idle();console.log('PASS actual title acquisition/takeover, counts, old owner, no duplicate or cash mutation');
 // Summon a forged creature through the selection API, then use the real render queue.
 r.turn=0;r.pending={};r.turnTransition=null;actor.hand=['orphe_f'];actor.pos=G.publicState(r,null).tiles.findIndex(t=>t.t==='land');G.resolveTile(r,actor);const pd=r.pending[actor.id];assert(pd.options.some(o=>o.id==='summon:orphe_f'));
 const res=await fetch(base+'/api/action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({room:r.code,playerId:actor.id,type:'choose',optionId:'summon:orphe_f',promptId:pd.promptId,turnEpoch:pd.turnEpoch,actionId:'milestone-summon'})});assert.equal(res.status,200,await res.text());assert.equal(r.owners[actor.pos].creature,'orphe_f');await render();await p.waitForSelector('#boardNotice[data-kind=ms-summon]:not([hidden])');
 assert.equal(await p.evaluate(()=>cameraOwner),null,'placement message appears before camera');assert(await p.evaluate(tile=>PW.debugCounts().hiddenPlacements.includes(tile),actor.pos),'new creature is hidden during message');assert.equal(await p.evaluate(tile=>PW.debugCounts().visibleCreatures[tile],actor.pos),false);assert.equal(await p.locator('.msCard review-game-card').getAttribute('card-id'),'orphe_f');assert.equal(await p.locator('.msEmptyLand .msElement').evaluate(e=>getComputedStyle(e).filter),'brightness(0) invert(1)');assert.equal(await p.locator('#summonCut.on').count(),0);assert(!(await p.locator('.msBody').innerText()).includes('自分の領地に'));await p.waitForTimeout(1300);await p.screenshot({path:path.join(out,'summon.png')});await idle();console.log('PASS actual summon selection/API -> forged card -> integrated notice without old cutin');
 // An actual battle win supplies the terrain, preserved level, and evolved identities.
 r.pending={};r.turn=0;r.turnTransition=null;actor.hand=['zati_f'];r.owners[21]={player:next.id,creature:'orphe',level:3,dmg:55};r.elemOv[21]='earth';G.startBattle(r,actor,21);Object.assign(r.battle,{atkCreature:'zati_f',supports:{[actor.id]:{kind:'support',cardId:'gweapon'},[next.id]:{kind:'none'}}});G.resolveBattle(r);assert(r.lastBattle.win);const battle=r.lastBattle;await render();
 await p.waitForSelector('#boardNotice[data-kind=ms-battle-result]:not([hidden])',{timeout:45000});assert.equal(await p.locator('#battle.on').count(),0);assert.equal(await p.locator('#boardNotice').getAttribute('data-actor'),actor.id);assert.equal(await p.locator('.msPrevious img[alt]').first().getAttribute('src'),'/assets/e_orphe.png');assert(await p.locator('.msLandBadge').evaluateAll(es=>es.every(e=>e.textContent.includes('Lv.3'))));await idle();console.log('PASS production battle win -> level/evolved result -> money queue');
 for(const width of [1440,1024]){await p.setViewportSize({width,height:width===1440?900:768});for(const [kind,e]of [['title',{title:'conqueror',player:next.id,previous:actor.id}],['summon',{tile:21,owner:{player:actor.id,creature:'orphe',level:3},element:'earth'}],['battle-result',battle],['battle-result',{...battle,win:false,remainHp:7}]]){
  await p.evaluate(({kind,e})=>{BoardNotice.reset();window.milestoneRun=BoardMilestones.present(kind,e,state,{ms:n=>n*.5});},{kind,e});await p.waitForTimeout(800);
  assert(await p.locator('#boardNotice img').evaluateAll(es=>es.every(e=>e.complete&&e.naturalWidth>0)));assert(await p.locator('.messageWindow,.msBody,.standName').evaluateAll(es=>es.every(e=>{const b=e.getBoundingClientRect();return b.left>=0&&b.right<=innerWidth+1&&b.top>=0&&b.bottom<=innerHeight+1&&e.scrollWidth<=e.clientWidth+1})));
  if(kind==='battle-result'&&!e.win){assert.equal(await p.locator('.msRemaining strong').innerText(),'7');assert.equal(await p.locator('#boardNotice').getAttribute('data-actor'),next.id);}
  await p.screenshot({path:path.join(out,`${kind}-${e.win??'none'}-${width}.png`)});await p.evaluate(()=>milestoneRun);
 }}
 await p.emulateMedia({reducedMotion:'reduce'});await p.evaluate(()=>{window.milestoneRun=BoardMilestones.present('title',{player:state.players[0].id,title:'conqueror'},state,{ms:n=>n*.2});});assert.equal(await p.locator('.msTitleIcon').evaluate(e=>getComputedStyle(e).animationName),'none');await p.evaluate(()=>milestoneRun);assert.deepEqual(errors,[]);console.log('PASS two sizes, images, evolved level summon, actual remaining HP, reduced motion, no browser errors');
}finally{await browser?.close();G.server.closeAllConnections();G.server.close();}})().catch(e=>{console.error(e);process.exit(1)});
