const assert=require('assert/strict'),fs=require('fs'),vm=require('vm');
const shown=[],ctx={window:{},structuredClone,BoardNotice:{effect:(m)=>shown.push(m)}};
vm.runInNewContext(fs.readFileSync('public/board-effects.js','utf8'),ctx);
const fx=ctx.window.BoardEffects,queue=[];
let state={code:'TEST',stateInstanceId:'one',players:[{id:'a',name:'発動者',charId:'mio'},{id:'b',name:'テスト八文字名前',charId:'adel'}],catalog:{CREATURES:{toxy:{name:'トキシー'},toxy_f:{name:'マッドミスト'}}},toxyNotices:[]};
const opts={queue:(priority,run,meta)=>queue.push({run,meta}),current:()=>state,ms:n=>n};
fx.observeToxy(state,opts);
state.toxyNotices=[{player:'a',target:'b',creature:'toxy',count:1,beforeCount:2,afterCount:1,at:1},{player:'a',target:'b',creature:'toxy_f',count:1,beforeCount:1,afterCount:0,at:2}];
fx.observeToxy(state,opts);fx.observeToxy(state,opts);
assert.equal(queue.length,2);assert.notEqual(queue[0].meta.id,queue[1].meta.id);
queue.forEach(e=>e.run());assert.equal(shown.length,2);
assert.match(shown[0].html,/瘴気連鎖/);assert.match(shown[0].html,/テスト八文字名前/);
assert.match(shown[0].html,/手札を捨てる/);assert.match(shown[1].html,/e_toxy.png/);
assert.match(shown[1].html,/0枚/);assert.equal(shown[0].actor,'a');
state={...state,stateInstanceId:'restored'};queue[0].run();assert.equal(shown.length,2);
fx.observeToxy(state,opts);assert.equal(queue.length,2,'restoration skips old notices');
state.toxyNotices=[...state.toxyNotices,{...state.toxyNotices[0],at:3}];fx.observeToxy(state,opts);
assert.equal(queue.length,3);queue[2].run();assert.equal(shown.length,3);
console.log('PASS Toxy notice: chained events, deduplication, restored scope, public counts, actor/target and evolved art');
state.catalog.CREATURES.kamadoma={name:'カマドーマ'};state.catalog.CREATURES.kamadoma_f={name:'ダイテッカン'};
state.kamadomaNotices=[];fx.observeKamadoma(state,opts);
state.kamadomaNotices=[{player:'a',creature:'kamadoma',count:1,reason:'summon',at:4},
 {player:'a',creature:'kamadoma_f',count:1,reason:'battle',at:5}];
fx.observeKamadoma(state,opts);fx.observeKamadoma(state,opts);
assert.equal(queue.length,5);assert.equal(queue[3].meta.kind,'kamadoma');
queue[3].run();queue[4].run();assert.match(shown[3].html,/武具錬成/);
assert.match(shown[3].html,/card-id="weapon"/);assert.match(shown[3].html,/手札に追加/);
assert.match(shown[4].html,/e_kamadoma.png/);assert.equal(shown[4].actor,'a');
state={...state,stateInstanceId:'third'};fx.observeKamadoma(state,opts);queue[4].run();
assert.equal(queue.length,5);assert.equal(shown.length,5,'restored/old Sword rewards do not replay');
console.log('PASS Kamadoma notice: fixed Sword card, actor, evolution, independent events, deduplication and restore');
